### ISSUE TITLE
Streaming Data Example Version used

### ISSUE THREAD

**Issue by H-Ribeiro** [piccolomo/plotext#14]
Hi, 
Using the latest version 2.2.2 with Streaming Data Example gives the following error:

> **AttributeError: 'function' object has no attribute 'scatter'**

I can tell that the syntax has changed since.

What is the most optimised version to use this example?

**Comment by H-Ribeiro** [comment]
Alternately could you update the example.
Thanks

**Comment by H-Ribeiro** [comment]
After some trial and error found that version 2.2.1 is the most optimised for that example.

**Comment by piccolomo** [comment]
Hi Enrique, thanks for the query. I will properly answer you as soon as
possible.
Regards

**Comment by piccolomo** [comment]
Hi Enrique, 

thanks for your reply. I have tested that code and it worked fine on my machine with version 2.2.2 (the current most updated one).

Let me know if you have any other issues.

All the best
