### ISSUE TITLE
image plotting example fails

### ISSUE THREAD

**Issue by notionparallax** [piccolomo/plotext#95]
Calling the example one-liner from the docs on the image example, i.e.: 
```
python3 -c "import plotext as plt; path = 'cat.jpg'; plt.download(plt.test_image_url, path); plt.image_plot(path); plt.title('A very Cute Cat'); plt.show(); plt.delete_file(path)"
```

gives the error: `AttributeError: module 'plotext' has no attribute 'test_image_url'. Did you mean: 'test_image_path'?`

If I search the repo for 'test_image_url' ([like this](https://github.com/piccolomo/plotext/search?q=test_image_url)) It shows up 4 uses of that string in MD files, but none in python files.

If I run 

```
> plotext.test_image_path
'C:\\Users\\bdoherty\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\plotext\\_data\\adam.jpg'
```

So, is the intent that you get a nice cat when you run `plt.test_image_url` or that you get the adam picture when you run `plt.test_image_path`

Happy to have a crack at a PR if you like

**Comment by piccolomo** [comment]
Hi @notionparallax, you are right, I worked on next version and already updated the guide, but not the files, I should do that soon. In the mean time the image example that would work with version 5.0 should be: ` import plotext as plt; plt.image_plot(plt.test_image_path); plt.show()`
Same for gif and videos: `import plotext as plt; plt.play_gif(plt.test_gif_path); plt.show()`
videos: import plotext as plt; plt.play_video(plt.test_video_path, from_youtube=True); plt.show()
youtube: `import plotext as plt; plt.play_youtube(plt.test_youtube_url); plt.show()`

**Comment by piccolomo** [comment]
quick message, new github version now available...

**Comment by piccolomo** [comment]
Hi @notionparallax,

Hello @PhilipVinc  ,

I have should have solved this issue in the new [version 5.1](https://github.com/piccolomo/plotext), available only on GitHub for now, using:
```console
pip install git+https://github.com/piccolomo/plotext
```

Any feedback or double test is appreciated.
Thanks and all the best,
Savino
