### ISSUE TITLE
from_matplotlib() Not Working with matplotlib 3.6

### ISSUE THREAD

**Issue by luator** [piccolomo/plotext#133]
It seems `from_matplotlib()` does not work anymore for the latest version of matplotlib.

I can run the [example from the documentation](https://github.com/piccolomo/plotext/blob/master/readme/environments.md#matplotlib) in an environment with matplotlib 3.5.3 installed and it is working as expected.

However, in an other (otherwise identical) environment with the latest matplotlib version 3.6.0 it fails with this error:
```
Traceback (most recent call last):
  File "/tmp/plttest.py", line 22, in <module>
    plx.from_matplotlib(fig)
  File "/usr/local/lib/python3.8/site-packages/plotext/_core.py", line 309, in from_matplotlib
    return _glob.from_matplotlib(fig)
  File "/usr/local/lib/python3.8/site-packages/plotext/_global.py", line 182, in from_matplotlib
    p = sub.get_geometry()[2]
AttributeError: 'AxesSubplot' object has no attribute 'get_geometry'
```

This is using plotext 5.2.7 in both cases.

**Comment by piccolomo** [comment]
Thanks a lot for reporting! I will look this up, I am out of plotext for awhile, but will update!

**Comment by piccolomo** [comment]
Hi @luator,

I updated the `from_matplotlib()` function to allow compatibility with `matplotlib` 3.6 without affecting compatibility with version 3.5. 
It worked on my system, but if issue persists please keep updated.

The new GitHub version 5.2.8 could be installed using: `pip install git+https://github.com/piccolomo/plotext`.

Thanks a lot for the issue report, and any other bug report is very welcomed.

All the best,
Savino

**Comment by luator** [comment]
Cool, thanks a lot!  I can confirm that it is now working with matplotlib 3.6.
